CBV/CVB/urls.py
from django.contrib import admin
from django.urls import path, include

import post


urlpatterns = [
    path("admin/", admin.site.urls),
    path("post/", include('post.urls')),
    path("books/", include('books.urls', namespace='bookapp')),
]

CBV/books/urls.py
from django.urls import path 
# from .views import  IndexDetail 
from .views import BookDetail, IndexDetail, ListBookView , TagView, AddBookView, BookEditView


app_name = 'book'

urlpatterns = [
    # path('', IndexDetail.as_view(), name='index'),
    path('', ListBookView.as_view(), name='index'),
    path('add/', AddBookView.as_view(), name='index'),
    # path('<slug:slug>/', BookDetail.as_view(), name='book-detail')  ,
    # path('<slug:slug>/edit/', BookEditView.as_view(), name='book-detail')  ,
    path('<int:pk>/', BookDetail.as_view(), name='book-detail')  ,
    path('<int:pk>/edit/', BookEditView.as_view(), name='book-detail')  ,  
    
    path('g/<str:genre>/', TagView.as_view())  ,
]

CBV/post/urls.py
from django.urls import path
from django.views.generic.base import TemplateView, RedirectView
from .views import MyView, PostPreLoad, SinglePost


app_name = 'post'

urlpatterns = [
    path('ex1/', TemplateView.as_view(template_name='ex1.html', extra_context={'title':'hello world'})),
    path('ex2/', MyView.as_view() ),
    path('rdt/', RedirectView.as_view(url='https://www.google.com'), name='go to Google'), 
    path('ex3/<int:pk>', PostPreLoad.as_view(), name='preload'), 
    path('ex4/<int:pk>', SinglePost.as_view(), name='single_post'), 
]

CBV/books/models.py
from django.db import models
from django.utils.text import slugify



class Book(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    count = models.IntegerField(null=True, default=0) 


    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        
        return super().save(*args, **kwargs)

CBV/post/models.py
from django.db import models



class Post(models.Model):
    name = models.CharField(max_length=100)
    count = models.IntegerField(null=True)

CBV/books/forms.py
from django import forms
from .models import Book

class AddForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'genre', 'author', 'isbn')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'from-control'}),
            'genre': forms.TextInput(attrs={'class': 'from-control'}),
            'author': forms.TextInput(attrs={'class': 'from-control'}),
            'isbin': forms.TextInput(attrs={'class': 'from-control'}),
        }

CBV/books/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.utils import timezone
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.detail import  DetailView
from django.views.generic.list import  ListView
from django.views.generic.edit import  FormView, CreateView, UpdateView
from .models import Book
from .forms import AddForm
from django.db.models import F


class IndexDetail(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all()

        return context
    

# class BookDetail(DetailView):
#     model = Book


class BookDetail(DetailView):
    model = Book
    template_name = 'book-detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Book.objects.filter(slug=self.kwargs['slug'])
        post.update(count=F('count') + 1)

        context['time'] = timezone.now()

        return context
    


class ListBookView(ListView):
    model = Book
    template_name = 'index.html'
    context_object_name = 'books'
    paginate_by = 1
    # paginate_by = 2  
    # queryset = Book.objects.all()[:2] ---> this equal to override  get_queryset function 

    # def get_queryset(self) -> QuerySet[Any]:
    #     return Book.objects.all()[:2]
    


class TagView(ListView):
    model = Book
    template_name = 'index.html'
    context_object_name = 'books'
    paginate_by = 1

    def get_queryset(self, *args, **kwargs) -> QuerySet[Any]:
        return Book.objects.filter(genre__icontains=self.kwargs.get('genre'))
    

# class AddBookView(FormView):
#     template_name = 'add.html'
#     success_url = '/books/'
#     form_class = AddForm

#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)



class AddBookView(CreateView):
    model = Book
    template_name = 'add.html'
    success_url = '/books/'
    # fields = ['title']
    form_class = AddForm

    def get_initial(self, *args, **kwargs) -> dict[str, Any]:
        intial = super().get_initial( **kwargs)
        intial['title'] = 'Enter Title'

        return intial
    


class BookEditView(UpdateView):
    model = Book
    template_name = 'add.html'
    success_url = '/books/'
    # fields = ['title']
    form_class = AddForm

CBV/post/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView, RedirectView
from post.models import Post
from django.db.models import F



class MyView(TemplateView):
    template_name = 'ex2.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = Post.objects.get(id=1)
        context['name'] = Post.objects.get(id=1).name
        return context


class PostPreLoad(RedirectView):
    pattern_name = 'post:single_post' # which page will he redirect to (single post)

    #  evey time anyone got post url increase count by one 
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        post = Post.objects.filter(pk=kwargs['pk']) 
        post.update(count=F('count') + 1)   

        return super().get_redirect_url(*args, **kwargs)


class SinglePost(TemplateView):
    template_name = 'ex3.html' # which page will be rendered

    # override get_context_data which responsible of get context data
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['title'] = get_object_or_404(Post, pk = kwargs['pk']) 
        
        
        return context

CBV/books/templates/add.html
{% extends "base.html" %} {% block content %}
<div class="container" style="max-width: 600px">
  <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">All Books</h1>
    <p class="lead">
      A range of wonderful programming books to help you learn JavaScript.
    </p>
  </div>
  <div class="py-5">
    <div class="row">
      <div class="col-12">
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <input type="submit" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

CBV/books/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome to Books {% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

CBV/books/templates/book-detail.html
    {% extends "base.html" %}
    {% block content %}
    <div class="container" style="max-width:800px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{book.title}}</h1>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{book.genre}}</small>
                <small class="text-muted">{{book.isbn}}</small>
                <small class="text-muted">{{time}}</small>
            </div>
        </div>

    </div>
    {% endblock %}

CBV/books/templates/books/book_detail.html
    {% extends "base.html" %}
    {% block content %}
    <div class="container" style="max-width:800px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{book.title}}</h1>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{book.genre}}</small>
                <small class="text-muted">{{book.isbn}}</small>
                <small class="text-muted">{{time}}</small>
            </div>
        </div>

    </div>
    {% endblock %}

CBV/books/templates/index.html
    {% extends "base.html" %}
    {% block content %}
    <div class="container">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">All Books</h1>
            <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
        </div>
        <div class="py-5">
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    {% comment %} <a class="text-dark" href="{% url 'bookapp:book-detail' slug=book.slug %}"> {% endcomment %}
                    <a class="text-dark" href="{% url 'bookapp:book-detail' pk=book.pk %}">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                    {{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted">{{book.genre}}</small>
                                    <small class="text-muted">{{book.isbn}}</small>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
     <div class="row">
                <div class="col-12">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

CBV/post/templates/ex1.html
{{title}}

<hr/>

<a href={% url 'post:go to Google'%}>go to Google<a />

CBV/post/templates/ex2.html
{{name}}

<hr / >


<a href={% url 'post:preload' pk=title.id%}>{{title.name}}<a />

CBV/post/templates/ex3.html
{{title.name}}